# Generated by Django 5.0.6 on 2024-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('Paid', models.BooleanField()),
            ],
        ),
    ]
