# Generated by Django 5.0.6 on 2024-07-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='course_files/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.courses')),
            ],
        ),
    ]
